export const PICTURES_DB_KEY = 'pictures';

export const SAVE_PICTURES_TO_SESSION = 'SAVE_PICTURES_TO_SESSION';

export const SAVE_PICTURES_TO_DB_START = 'SAVE_PICTURES_TO_DB_START';
export const SAVE_PICTURES_TO_DB_SUCCESS = 'SAVE_PICTURES_TO_DB_SUCCESS';
export const SAVE_PICTURES_TO_DB_FAILURE = 'SAVE_PICTURES_TO_DB_FAILURE';

export const LOAD_PICTURES_FROM_DB_START = 'LOAD_PICTURES_FROM_DB_START';
export const LOAD_PICTURES_FROM_DB_SUCCESS = 'LOAD_PICTURES_FROM_DB_SUCCESS';
export const LOAD_PICTURES_FROM_DB_FAILURE = 'LOAD_PICTURES_FROM_DB_FAILURE';

export const INCREASE_PICTURE_RATING = 'INCREASE_PICTURE_RATING';
export const DECREASE_PICTURE_RATING = 'DECREASE_PICTURE_RATING';
